server:
  port: 9005
spring:
  jackson: #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  rabbitmq:
    host: 192.168.123.146
    port: 5672
    username: llzelin
    password: Zl150168
    virtual-host: /
