server:
  port: 9005
spring:
  jackson: #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  rabbitmq:
    host:
    port: 5672
    username: 
    password: 
    virtual-host: /
